In [19]:
!pip install selenium

Collecting selenium
  Downloading selenium-4.19.0-py3-none-any.whl (10.5 MB)
     ---------------------------------------- 10.5/10.5 MB 5.5 MB/s eta 0:00:00
Collecting typing_extensions>=4.9.0
  Downloading typing_extensions-4.11.0-py3-none-any.whl (34 kB)
Collecting trio-websocket~=0.9
  Downloading trio_websocket-0.11.1-py3-none-any.whl (17 kB)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (from selenium) (2023.5.7)
Collecting trio~=0.17
  Downloading trio-0.25.0-py3-none-any.whl (467 kB)
     -------------------------------------- 467.2/467.2 kB 7.3 MB/s eta 0:00:00
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (from selenium) (1.26.14)
Collecting outcome
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Collecting exceptiongroup
  Downloading exceptiongroup-1.2.0-py3-none-any.whl (16 kB)
Requirement already satisfied: sortedcontainers in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: cffi>=1.14 in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Collecting attrs>=23.2.0
  Downloading attrs-23.2.0-py3-none-any.whl (60 kB)
     ---------------------------------------- 60.8/60.8 kB 3.4 MB/s eta 0:00:00
Collecting sniffio>=1.3.0
  Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Requirement already satisfied: idna in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Collecting wsproto>=0.14
  Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Collecting h11<1,>=0.9.0
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ---------------------------------------- 58.3/58.3 kB 3.0 MB/s eta 0:00:00
Installing collected packages: typing_extensions, sniffio, h11, exceptiongroup, attrs, wsproto, outcome, trio, trio-websocket, selenium
  Attempting uninstall: typing_extensions
    Found existing installation: typing_extensions 4.4.0
    Uninstalling typing_extensions-4.4.0:
      Successfully uninstalled typing_extensions-4.4.0
  Attempting uninstall: sniffio
    Found existing installation: sniffio 1.2.0
    Uninstalling sniffio-1.2.0:
      Successfully uninstalled sniffio-1.2.0
  Attempting uninstall: attrs
    Found existing installation: attrs 22.1.0
    Uninstalling attrs-22.1.0:
      Successfully uninstalled attrs-22.1.0
Successfully installed attrs-23.2.0 exceptiongroup-1.2.0 h11-0.14.0 outcome-1.3.0.post0 selenium-4.19.0 sniffio-1.3.1 trio-0.25.0 trio-websocket-0.11.1 typing_extensions-4.11.0 wsproto-1.2.0

In [23]:
import pandas as pd
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
import warnings
warnings.filterwarnings('ignore')
import time

In [26]:
driver1=webdriver.Chrome()
driver1.get("https://www.naukri.com/")


role=driver1.find_element(By.XPATH,'/html/body/div[1]/div[7]/div/div/div[1]/div/div/div/div[1]/div/input')
role.send_keys("Data Scientist")


role_search=driver1.find_element(By.XPATH,'/html/body/div[1]/div[7]/div/div/div[6]')
role_search.click()

In [29]:
location_filter = driver1.find_element(By.XPATH, '/html/body/div/div/main/div[1]/div[1]/div/div/div[2]/div[6]/div[2]/div[3]/label/p/span[1]')
location_filter.click()

In [ ]:
salary_filter=driver1.find_element(By.XPATH,'/html/body/div/div/main/div[1]/div[1]/div/div/div[2]/div[3]/div[2]/div[2]/label/p/span[1]')
salary_filter.click()

In [31]:
job_title=[]
job_location=[]
company_name=[]
exp_req=[]

In [32]:
title_tags=driver1.find_elements(By.XPATH,'//div[@class="cust-job-tuple layout-wrapper lay-2 sjw__tuple "]/div[1]')

for i in title_tags:
    job_title.append(i.text)
    

loc_tags=driver1.find_elements(By.XPATH,'//span[@class="locWdth"]')

for i in loc_tags:
    job_location.append(i.text)
    

company_tags=driver1.find_elements(By.XPATH,'//div[@class=" row2"]/span/a[1]')

for i in company_tags:
    company_name.append(i.text)
    
    
exp_tags=driver1.find_elements(By.XPATH,'//span[@class="expwdth"]')


for i in exp_tags:
    exp_req.append(i.text)

In [33]:
print(len(job_title),len(job_location),len(company_name),len(exp_req))

20 20 20 20

In [34]:
df1=pd.DataFrame({"Job_title":job_title,"Job_location":job_location,"Company_name":company_name,"Experience_req":exp_req})
df1

,Job_title,Job_location,Company_name,Experience_req
0,"Data Scientist, Marketing","Hyderabad/Secunderabad, Bangalore/Bengaluru, K...",Coursera,4-6 Yrs
1,Data Scientist,"Hyderabad, Bengaluru, Kolkata, Mumbai, New Del...",Ford,3-6 Yrs
2,GenAI Data Scientist,"Hyderabad, Bengaluru, Kolkata, Mumbai, New Del...",Ford,5-6 Yrs
3,Data Scientist-Senior Associate - P&T Labs,"Hyderabad, Bengaluru, Mumbai",PwC Service Delivery Center,4-6 Yrs
4,Senior Analyst- Clinical Data Management Scien...,Bengaluru,Accenture,5-8 Yrs
5,Data Scientist,Bengaluru,Infosys,3-5 Yrs
6,Data Scientist,"Hyderabad, Bengaluru, Kolkata, Mumbai, New Del...",Kashsam Data Solutions,3-7 Yrs
7,NLP Data Scientist - Real World Data (RWD),"Hyderabad/Secunderabad, Bangalore/Bengaluru, K...",Agilite Global Solutions,7-8 Yrs
8,Data Scientist II,"Bengaluru, Greater Noida",Honeywell,4-6 Yrs
9,Data Scientist,"Hyderabad, Bengaluru, Chennai",Wipro,5-10 Yrs
10,Data Scientist III,Bengaluru,Walmart,4-9 Yrs
11,Data Scientist,"Hyderabad, Bengaluru, Kolkata, Mumbai, New Del...",Scienaptic Systems,2-7 Yrs
12,Data Scientist 2,Bengaluru,Paypal,6-10 Yrs
13,Sr Data Scientist,Bengaluru,IBM,8-12 Yrs
14,Data Scientist,Bengaluru,Siemens,2-3 Yrs
15,Data Scientist,"Bengaluru, Noida, Gurugram",Novitas Infotech,3-7 Yrs
16,Data Scientist,"Bengaluru, Gurugram",Blackbuck,3-7 Yrs
17,Data Scientist,Bengaluru,Applied Materials,4-7 Yrs
18,Data Scientist,Bengaluru,Applied Materials,4-7 Yrs
19,Data Scientist,Bengaluru,Volvo Financial Services,3-6 Yrs

In [49]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (4.19.0)
Requirement already satisfied: trio~=0.17 in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (from selenium) (0.25.0)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (from selenium) (2023.5.7)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (from selenium) (4.11.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (from selenium) (1.26.14)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: sortedcontainers in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: outcome in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: idna in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: exceptiongroup in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: cffi>=1.14 in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: attrs>=23.2.0 in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (from trio~=0.17->selenium) (23.2.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\sharma.akash\appdata\local\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [50]:
import pandas as pd
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
import warnings
warnings.filterwarnings('ignore')
import time

In [56]:
driver1=webdriver.Chrome()
driver1.get("https://www.shine.com/")

In [ ]:
role=driver1.find_element(By.XPATH,'/html/body/div[1]/div[7]/div/div/div[1]/div/div/div/div[1]/div/input')
role.send_keys("Data Scientist")

In [ ]:
role_search=driver1.find_element(By.XPATH,'/html/body/div[1]/div[7]/div/div/div[6]')
role_search.click()

In [ ]:
location_filter = driver1.find_element(By.XPATH, '/html/body/div/div/main/div[1]/div[1]/div/div/div[2]/div[6]/div[2]/div[3]/label/p/span[1]')
location_filter.click()

In [ ]:
job_title=[]
job_location=[]
company_name=[]
exp_req=[]

In [ ]:
title_tags=driver1.find_elements(By.XPATH,'//div[@class="cust-job-tuple layout-wrapper lay-2 sjw__tuple "]/div[1]')

for i in title_tags:
    job_title.append(i.text)
    

loc_tags=driver1.find_elements(By.XPATH,'//span[@class="locWdth"]')

for i in loc_tags:
    job_location.append(i.text)
    

company_tags=driver1.find_elements(By.XPATH,'//div[@class=" row2"]/span/a[1]')

for i in company_tags:
    company_name.append(i.text)
    
    
exp_tags=driver1.find_elements(By.XPATH,'//span[@class="expwdth"]')


for i in exp_tags:
    exp_req.append(i.text)

In [ ]:
print(len(job_title),len(job_location),len(company_name),len(exp_req))

In [ ]:
df1=pd.DataFrame({"Job_title":job_title,"Job_location":job_location,"Company_name":company_name,"Experience_req":exp_req})
df1